include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT atim2203@gmail.com)
set(CPACK_PACKAGE_VERSION_MAJOR ${area_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${area_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${area_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${area_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${area_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static C++ library for areaing")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_RPM_PACKAGE_NAME "area-devel")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "area")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libarea-dev")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
